[package]
name = "makepad-widgets"
version = "1.0.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad widgets"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "N0YGjn7dnhc4DEHmww9lwuYwMVI="

[dependencies]
makepad-draw = { path = "../draw", version = "1.0.0" }
makepad-derive-widget = {path = "./derive_widget", version="1.0.0"}





serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = []
## Enables certain public-facing types to derive serde serialization traits.
serde = ["dep:serde", "makepad-draw/serde", "makepad-derive-widget/serde"]
